### PR TITLE
Project Card and Tags Changes

### PR DESCRIPTION
**Pull request by chirag828049**
See commit message for changes.

### CODE REVIEW

**Comment by chirag828049** [comment]
@sahil-shubham this will work i guess ?

**Comment by chirag828049** [comment]
P.S. Was experimenting on the random colors. Will something like this look good ?
image

**Comment by rajivharlalka** [comment]
LGTM just a suggestion, having same color in adjacent projects looks a bit odd, can a bit more contrast between the lighter and darker shade would look better imo, rest is fine

**Comment by chirag828049** [comment]
Currently I am using random selection of colors. we can, on the other hand,  use something like RGBGRGBGRGBG.....

**Comment by sahil-shubham** [comment]
Let me play around in this PR, nice work till now @chirag828049 I will merge it when I am done.

**Pull request merged**
