### PR TITLE
Added 404 Page

### LINKED ISSUE #192: Add 404 Page
Self explanatory.

### PR DESCRIPTION
**Pull request by snowden-fu**
this is effect while accessing `/hello` #192 
Screenshot 2023-11-28 at 19 30 23

### CODE REVIEW

**Review by harshkhandeparkar — CHANGES_REQUESTED** [review]
Is it possible to add a "Go Back" button or "Go to Home" button below the 404? Also it would look better if the 404 was bigger and at the center of the page.

**Comment by snowden-fu** [comment]
> Is it possible to add a "Go Back" button or "Go to Home" button below the 404? Also it would look better if the 404 was bigger and at the center of the page.

" Going back to home " can directly click `Logo` in `Header`.

**Comment by snowden-fu** [comment]
@harshkhandeparkar would you like to give a UI prototype for this page design?

**Comment by harshkhandeparkar** [comment]
> > Is it possible to add a "Go Back" button or "Go to Home" button below the 404? Also it would look better if the 404 was bigger and at the center of the page.
> 
> " Going back to home " can directly click `Logo` in `Header`.

It would still be better to add a button.

**Comment by harshkhandeparkar** [comment]
> @harshkhandeparkar would you like to give a UI prototype for this page design?

Let it be for now, it's not a necessity. Thank you!

**Review by harshkhandeparkar — APPROVED** [review]

**Pull request merged**
