### PR TITLE
Faq search feature

### PR DESCRIPTION
**Pull request by aniketpathak028**
# FAQ search feature

**Fixes** #10 

**Implementing a search feature to search a given query on the FAQ page.**

https://user-images.githubusercontent.com/74519511/146390159-d500b9d9-ca5b-4267-9edb-e96f8bf7936a.mp4

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@sahil-shubham

**Comment by sahil-shubham** [comment]
This works so well! Thanks for putting in the time to help us with this @aniketpathak028 This feature is very helpful in the long run.

So the reason behind the links not being shown as links is because they are written in markdown, we render FAQ as markdown because markdown is easier to write in. It would be good for future if we can implement search while sticking with markdown, what do you think? 

Would you like to think of some way through which can keep using markdown but can also search through things? Let me know when you have tried from your side and we can solve the problem together.

**Comment by aniketpathak028** [comment]
Hey @sahil-shubham  , 

Thanks for that suggestion, I had a look into it and apparently figured that traditionally we were fetching all the data from faq.md file and then rendering it as HTML using the react-markdown package, which is a great idea. However, unfortunately, Fuse.js doesn't seem to work with Markdowns and needs a JSON file. 

So, I used a package called html-react-parser and enclosed all the links with anchor tags in the JSON file, such that when we render we use this parser and the links get rendered as links. It seems to be working fine and gets the job done. However if there is any better way of doing the same, do let me know, I'll try to implement it. : )



https://user-images.githubusercontent.com/74519511/146563166-aca763f4-973d-4c46-978b-8fe6a42d9d69.mp4

**Comment by sahil-shubham** [comment]
I am going ahead with merging this @aniketpathak028 Thank you for being patient and putting all this effort into achieving the goal of rendering markdown as well as searching through it. 

To have the searching functionality for now, I am going to compromise the markdown rendering. I will see if I can work out a solution.

**Pull request merged**
