### PR TITLE
Changing the cursor icon #208

### PR DESCRIPTION
**Pull request by julesglad**

### CODE REVIEW

**Comment by Nafisay** [comment]
#208

**Comment by Nafisay** [comment]
#208 @julesglad please refrain from making a pr before the issue has been assigned to you. Kindly adhere to the rules given here [https://github.com/kossiitkgp/KWoC-Frontend/blob/truth-redefined-again/CONTRIBUTING.md#guidelines](https://github.com/kossiitkgp/KWoC-Frontend/issues/url)

**Comment by julesglad** [comment]
@Nafisay  Sorry about that, first time attempting to do open source so I must have missed it in my excitement. Still trying to figure out all the steps that go with this.

**Comment by Nafisay** [comment]
> @Nafisay Sorry about that, first time attempting to do open source so I must have missed it in my excitement. Still trying to figure out all the steps that go with this.

It's alright!

**Pull request closed without merging**
