### PR TITLE
Added more features in Project form

### PR DESCRIPTION
**Pull request by rakaar**
Fixes - #6 #5 #4 #3 
image
The tags are filled from topics, languages used and can be further edited - added/removed
The branches are fetched and the user can select from any one of the branches for stats

image
New field added, need to integrate in the future when the endpoint is made. Left comments at the appropriate place where endpoint calls need to be made

image
`Why this?` - It is a tool tip explaining why what exactly branch for stats mean. It is important to explain as many might not be aware? Any other ideas than tool tip? It seemed unresponsive in Mobile.

Some more changes made in proj form filling are
- First only 3 fields are visible - link, name, desc
- after link is filled. These fields - tags, branches, communication link become visible.
- til communication link is not a proper link, submit button won't be available
- The form will be submitted only when all the fields, except secondary mentor has been field. Seconady mentor field is optional!
- README is also being fetched from the repo, we will display the readme on the projects page
- changed a lot of old funcs and added docs to some of the important funcs

To test
- In console- `localStorage.setItem('mentor_username', 'xypnox')`
- In console - `localStorage.setItem('mentor_jwt', 'aaa')`
- Visit `http://localhost:3000/form/project`
- Use `todxpy` project for testing, as it has at least 2 issues and a README of size greater than minimum

### CODE REVIEW

**Comment by rakaar** [comment]
image
A not so serious issue, we can discuss later! We can fix CSS issues at the last moment too!
Any other ideas for order of fields - Name, Desc, Proj link, Tags, Branch, Communication Link, Seconady mentor,Submit
Note that after link is filled - the tags and branch fields appear and are autofilled

**Review by iamananya — APPROVED** [review]
The tooltip was awesome.Thank you for the changes.

**Review by sahil-shubham — CHANGES_REQUESTED** [review]
- The tooltip is a nice addition. I think it would be better if we make it on click on an [info icon](https://feathericons.com/?query=info) next to the headings of input fields because while testing I completely missed the tooltip. Having the icon seems better than `why this?` and making it appear on click would make it appear on mobile devices too. (width issues can be fixed after this is merged)
- One wouldn't know that the submit button is disabled without clicking on it, changing it's colour to grey while it's disabled would be a good indicator
- Let's make it clear in the form that the secondary mentor is optional, as the submit button told me to `Please fill all the fields of the form` which isn't quite correct here. 

I found this order more appropriate, although it's nothing that can't be fixed later: 
- Name
- Project Link 
- Description
- Communication Link
- Tags 
- Branch
- Secondary Mentor (if any)

###  Everything else looks pretty good to me, let's merge this after these small changes. Thank you. 
I hope doing KWoC work so early doesn't prevent those last moment coding sprints :p, I really liked those.

**Comment by rakaar** [comment]
@sahil-shubham 
- I added tooltip as u told, it is better  than `why this`, u were right
- Submit button is not even visible when its disabled. How can even people click on it?
image
- I changed the content of alert to `Please fill all the compulsory fields of the form(all except Secondary Mentor)`
- And regarding the order, I kept as u said except the position of `communication link`. I felt it should be after all the things related to project repo(till name,desc,link,tags,branch) are done. Hence I put it just before the `Secondary mentor`. Wat do u say?

**Comment by rakaar** [comment]
> I hope doing KWoC work so early doesn't prevent those last moment coding sprints :p, I really liked those.

lol, last moment kaam toh hamesha bacha rahega. For new and important features, better if we complete it now. Bcoz they take time to implement and test. So that we can during the end, we can only focus on small things!

**Comment by sahil-shubham** [comment]
- Submit button is not even visible when its disabled. How can even people click on it? 
It is visible to me, on both firefox and chrome. 

- Hence I put it just before the Secondary mentor. Wat do u say?
Sounds good to me. 

We can merge this now, I will take fix up the styling of the form and few other things after this is merged.

**Review by sahil-shubham — APPROVED** [review]
LGTM. Thank you.

**Comment by rakaar** [comment]
> It is visible to me, on both firefox and chrome.

You have some super powers may be!!! 🔥 🔥

**Comment by rakaar** [comment]
>  I will take fix up the styling of the form and few other things after this is merged.

We can save this for last moment sprints!!! :P
I am merging it then

**Pull request merged**
