### PR TITLE
Fixed the link for manual in FAQ page

### PR DESCRIPTION
**Pull request by Jigyasa-G**
The link for student manual which was earlier not clickable, has been added. Students will now be able to navigate easily through the FAQs to the required document

### CODE REVIEW

**Review by sahil-shubham — APPROVED** [review]
Thank you for adding this @Jigyasa-G This was important thing which we somehow missed. 

Can you also make the same change [here](https://github.com/kossiitkgp/KWoC-21-Frontend/blob/master/src/data/faq.json#L104), we recently added the feature for searching through FAQ, for which we needed a `json` file. You would have to add an anchor tag. We can merge this PR after this.

**Comment by Jigyasa-G** [comment]
I have made the suggested changes to the json file for PR #86

**Review by sahil-shubham — APPROVED** [review]
Thanks for implementing the suggested changes so quickly.

**Comment by Jigyasa-G** [comment]
> 

Glad to contribute !

**Pull request merged**
